### ISSUE TITLE
Can add graticule but cannot remove

### ISSUE THREAD

**Issue by DrPDash** [Leaflet/Leaflet.Graticule#6] opened 2019-02-24 21:50 UTC
Hi Folks, I could add the graticule with .addTo(map) function but cannot remove it using either .remove() or .removeFrom() function. The code is below. I'm likely missing something simple enough; any suggestion would be greatly appreciated. Thanks

lyrGraticule = L.latlngGraticule({
    showLabel: true,
    dashArray: [1, 1],
    zoomInterval: [
        {start: 1, end: 1, interval: 60},
        {start: 1.01, end: 2, interval: 45},
        {start: 2.01, end: 3, interval: 30},
        {start: 3.01, end: 4, interval: 15},
        {start: 4.01, end: 5, interval: 5},
        {start: 5.01, end: 20, interval: 1}
    ]
});
    ctlGraticule = L.easyButton('fa fa-th', function () {
                if (map.hasLayer(lyrGraticule)) {
                    lyrGraticule.removeFrom(map);
                };
                if (!map.hasLayer(lyrGraticule)) {
                    lyrGraticule.addTo(map);
                };
    }, 'show Graticule');
    map.addControl(ctlGraticule);

**Comment by IvanSanchez** [comment] 2019-02-24 23:07
Graticules can be removed without a problem, see https://plnkr.co/edit/VdCgLaO3rnYUhSeqteAc?p=preview

Not a bug, closing.

**Closed as completed by IvanSanchez** 2019-02-24 23:07 UTC

**Comment by DrPDash** [comment] 2019-02-25 02:04
Thanks, Ivan, my bad. The logical comparison was wrong and the variable declaration did not have a global scope.

This worked:
    ctlGraticule = L.easyButton('fa fa-th', function () {
         if (map.hasLayer(lyrGraticule) == false) {
            lyrGraticule.addTo(map);
        } else {
            lyrGraticule.remove();
        };
    }, 'show/hide Graticule');
    map.addControl(ctlGraticule);
